apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: robots.robot.llleon.io
spec:
  group: robot.llleon.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              deploymentName:
                type: string
              replicas:
                type: number
  names:
    kind: Robot
    plural: robots
    singular: robot
  scope: Namespaced
